version: "3.8"

services:
  frontend:
    image: yeagerai/simulator-frontend:${LOCALNETVERSION:-latest}
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    environment:
      - VITE_*
    env_file:
      - ./.env
    depends_on:
      jsonrpc:
        condition: service_healthy
    expose:
      - "${FRONTEND_PORT:-8080}"
    restart: always
    security_opt:
      - "no-new-privileges=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - frontend


  jsonrpc:
    image: yeagerai/simulator-jsonrpc:${LOCALNETVERSION:-latest}
    environment:
      - FLASK_SERVER_PORT=${RPCPORT:-5000}
      - PYTHONUNBUFFERED=1
      - RPCDEBUGPORT=${RPCDEBUGPORT:-5001}
      - WEBDRIVERHOST=${WEBDRIVERHOST:-webdriver}
      - WEBDRIVERPORT=${WEBDRIVERPORT:-4444}
    ports:
      - "${RPCPORT:-5000}:${RPCPORT:-5000}"
      - "${RPCDEBUGPORT:-5001}:${RPCDEBUGPORT:-5001}"
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "python3", "backend/healthcheck.py", "--port", "${RPCPORT}" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      database-migration:
        condition: service_completed_successfully
      webdriver:
        condition: service_healthy  
    expose:
      - "${RPCPORT:-5000}"
    restart: always
    security_opt:
      - "no-new-privileges=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: ${JSONRPC_REPLICAS:-1}
    volumes:
      - hardhat_artifacts:/app/hardhat/artifacts
      - hardhat_deployments:/app/hardhat/deployments


  webdriver:
    image: yeagerai/genlayer-genvm-webdriver:0.0.3
    shm_size: 2gb
    environment:
      - PORT=${WEBDRIVERPORT:-4444}
    expose:
      - "${WEBDRIVERPORT:-4444}"
    restart: always
    security_opt:
      - "no-new-privileges=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  ollama:
    image: ollama/ollama:0.6.6
    ports:
      - 11434:11434
    container_name: genlayer-ollama
    tty: true
    restart: always
    security_opt:
      - "no-new-privileges=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - ollama

  postgres:
    image: postgres:17-alpine
    ports:
      - "${DBPORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DBUSER:-postgres}
      - POSTGRES_PASSWORD=${DBPASSWORD:-postgres}
      - POSTGRES_DB=${DBNAME:-simulator_db}
    healthcheck:
      test: pg_isready -U ${DBUSER:-postgres} -d ${DBNAME:-simulator_db}
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    security_opt:
      - "no-new-privileges=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Uncomment the following lines if you want your DB to persist
    # volumes:
    #   - "./data/postgres:/var/lib/postgresql/data"

  database-migration:
    image: yeagerai/simulator-database-migration:${LOCALNETVERSION:-latest}
    environment:
      - DB_URL=postgresql://${DBUSER:-postgres}:${DBPASSWORD:-postgres}@postgres/${DBNAME:-simulator_db}
    depends_on:
      postgres:
        condition: service_healthy

  hardhat:
    image: yeagerai/simulator-hardhat:${LOCALNETVERSION:-latest}
    ports:
      - "${HARDHAT_PORT:-8545}:8545"
    environment:
      - HARDHAT_NETWORK=hardhat
    volumes:
      - hardhat_artifacts:/app/artifacts
      - hardhat_deployments:/app/deployments

volumes:
  hardhat_artifacts:
  hardhat_deployments: